# -*- coding: utf-8 -*-
"""Level-c supplementary translations: training texts (G12-G18, 34 uniques, official-PC
phrasing where available), pool-group dialogs 31-200B, MP map labels (G34-39/G53-57),
extra credit roles, legal keeps. Keys = exact original text (normed upper)."""
import re

def norm(s):
    s = s.replace('\x92', "'").replace('\xa0', ' ')
    return re.sub(r'\s+', ' ', s).strip()

T = {}
def _m(pairs):
    for en, zh in pairs:
        T[norm(en).upper()] = zh

# ---------------- training (G12-G18 uniques; official PC wording reused) ----------------
_m([
 ('The assault rifle is your primary infantry weapon.  Aim at a target and press the Fire Weapon Button to shoot.  Notice how the reticule changes size as you move and fire.  The smaller the reticule, the more accurate your shot will be.  Practice hitting the targets downrange.  If you run out of bullets, change magazines with the Reload Weapon Button.',
  '突击步枪是你的主要武器。瞄准目标然后按下开火键即可射击。注意你在移动和射击时准星的变化。准星越小射击就越精确。对下面的靶子练习一下射击。如果没有子弹了，按换子弹键更换弹夹。'),
 ('Use the Fire Weapon Button to place the claymore in the center of the blast pit.  Aim it toward the target dummies - it will face in the same direction you\'re facing when you place it.  When the claymore is ready, move to the safety of the blast bunker for detonation.',
  '用开火键将地雷放置在弹坑中央。把它对准靶子假人——放置时它会朝向你面对的方向。地雷放好后，退到安全的掩体里准备引爆。'),
 ('Press the Fire Weapon Button again to detonate the claymore.  The trigger works at any range.  Demolitions charges don\'t have triggers - they\'re set to go off on timers after you\'re clear of the blast area.  If a mission requires a demolitions charge to complete an objective, you\'ll be told about it in the briefing.',
  '再按一次开火键将地雷引爆。引爆器在任何距离都有效。定时炸弹没有引爆器——当你离开爆炸范围后它会在设定时间内自动爆炸。如果任务需要用定时炸弹完成目标，任务简报里会说明。'),
 ('This is the command range.  Here you will learn how to use the command interface to issue orders to the other soldiers of your platoon.  Press the START button at any time to exit training.',
  '这里是指挥训练区。你要学习如何使用指挥界面向小队的其他队员下达命令。随时按 START 键退出训练。'),
 ('This is the demolitions range.  Here you\'ll learn how to place a claymore antipersonnel mine and detonate it.  This same technique is used for placing demolitions charges and battlefield sensors.  Press the START button at any time to exit training.',
  '这里是爆破训练区。你要学习如何放置地雷并将之引爆。你可以用同样的方法来放置定时炸弹以及心跳感应器等。随时按 START 键退出训练。'),
 ('Open doors using the Perform Action Button.  Try to avoid standing directly in front of a door when you open it - it makes you a prime target for whoever\'s on the other side.',
  '用动作键来开门。开门的时候尽量不要正对着门——这可能使你马上成为门后敌人的靶子。'),
 ('Press the Fire Weapon Button to launch a grenade.  The standard grenade launcher needs to be reloaded after every shot.  Grenades fired from grenade launchers explode on impact, so don\'t try to bounce them around corners.',
  '按开火键来发射榴弹。标准的榴弹发射器每开一炮就要装一次弹。榴弹遭到撞击后会马上爆炸，所以不要试图让它在墙上反弹。'),
 ('This is the grenade range.  Here you\'ll learn how to throw hand grenades and fire a grenade launcher. Press the START button at any time to exit training.',
  '这里是榴弹训练区。你要学习如何投掷手雷和使用榴弹发射器。随时按 START 键退出训练。'),
 ('Tap the Fire Weapon Button to toss the grenade a short distance, or hold and release the Button for a long throw.  Notice that the reticule doesn\'t change size - grenades will go exactly where you throw them, but you\'ll need to learn to take the arc of your throw into account.  Practice lobbing grenades over the low wall in front of you, or hitting the targets in the far building.',
  '点击开火键能向较近的目标投掷手雷，按住再放开则可以投得更远。注意准星大小不会改变——手雷会落在你投掷的位置，但你要把抛物线的路径计算进去。练习把手雷投过前面的矮墙，或命中远处建筑里的目标。'),
 ('To use a fixed machine gun, stand in front of it and press the Perform Action Button.',
  '要使用固定的机枪，先站到它前面然后按动作键。'),
 ('Press the Fire Weapon Button to fire the machine gun.  Notice that you don\'t have a targeting reticule - use the tracers to walk your shots onto the target.  Practice shooting at the targets downrange.  When you\'re done firing, press the Perform Action Button to quit.',
  '按开火键来射击机枪。要注意的是固定机枪没有准星——靠曳光弹的弹道来修正瞄准。练习对下面的目标射击。射击结束后按动作键退出。'),
 ('This is the machine gun range.  Here you\'ll learn how to fire a fixed machine gun.  Press the Start Button at any time to exit training.',
  '这里是机枪训练区。你要学习如何使用固定的机枪。随时按 START 键退出训练。'),
 ('The obstacle course will teach you how to move through the world.  Use the left analog stick to move forward and back and side-to-side.  Use the right analog stick to turn, and look up and down.  Press the left analog stick hard to run.  Press the START button at any time to exit training.',
  '越野训练将教你如何在场景中移动。用左摇杆前后左右移动，用右摇杆转身和调整视角上下。用力推左摇杆即可奔跑。随时按 START 键退出训练。'),
 ('The route to the next training range is through this darkened hallway.  Switch on your night vision goggles with the Night Vision Button.  Night vision is essential in low-light situations, but you\'ll see better in full illumination with it switched off.  When you leave the darkened area, press the Night Vision Button again to switch it off.',
  '通往下一个训练区的路要穿过这条黑暗的走廊。按夜视镜键打开夜视仪。夜视仪在光线昏暗时必不可少，但在光线充足的地方关掉它看得更清楚。离开黑暗区域后，再按一次夜视镜键将其关闭。'),
 ('When you\'re standing still you can peek around obstacles.  Press the Left and Right Peek Buttons and practice using the barrier.  Remember, the smaller the target you present to the enemy, the harder for you to get hit.',
  '站立不动时你可以窥视障碍物两侧。按左窥视和右窥视键，利用掩体练习。记住，你暴露给敌人的目标越小，就越难被击中。'),
 ('In addition to his primary weapon, every soldier can carry one secondary weapon.  You can switch between the primary and secondary by pressing the Change Equipment Button.  Switch to the pistol and practice hitting the short-range targets.',
  '除了主要武器外，每个士兵都还装备了备用武器。按更换装备键可以在主副武器之间切换。切换到手枪，练习向近距离的目标射击。'),
 ('Notice how the rocket reticule differs from the rifle and grenade reticules.  With rockets you can\'t fire the weapon until the reticule reaches its minimum size.  Wait for the reticule to converge, then press the Fire Weapon Button.  The standard rocket launcher needs to be reloaded after every shot.',
  '你应该注意到火箭筒的准星和步枪与手雷的都不一样。你必须要等准星变成最小的时候才能开火。等准星收缩到最小后再按开火键。标准的火箭发射器每发射一枚就要装一次弹。'),
 ('This is the rocket range.  Here you\'ll learn how to fire antitank rockets. Press the START button at any time to exit training.',
  '这里是火箭筒训练区。你要学习如何使用反坦克火箭筒。随时按 START 键退出训练。'),
 ('The only way to destroy a tank or other armored vehicle is with an antitank rocket - so be sure to equip your team with them if the mission briefing indicates you\'re going up against armor.  And remember that rockets have a backblast - if you fire a rocket when there are friendlies standing behind you, you\'ll take them out as well.',
  '摧毁坦克和其它装甲车辆的唯一办法就是使用反坦克火箭筒——如果任务简报里提到要对付装甲车，别忘了给你的队员装备上火箭筒。同时要记住火箭筒的尾部也会爆炸——如果你开火时身后有队友，他们也会被烧伤。'),
 ('This is the small arms range.  Here you\'ll learn how to fire a rifle and a pistol, how to switch weapons, reload and use a scope. Press the START button at any time to exit training.',
  '这里是轻武器训练区。你要学习如何使用步枪和手枪，如何切换武器、换弹和使用瞄准镜。随时按 START 键退出训练。'),
 ('The sniper rifle is equipped with a scope for long-range shots.  Use the Zoom In/Out buttons for continuous zoom control.  Practice hitting the long-range targets.',
  '狙击步枪装有用于远距离射击的瞄准镜。用放大/缩小键进行连续变焦。练习命中远距离的目标。'),
 ('In addition to standing upright, you can crouch and go prone.  When you\'re on the battlefield, keeping your head down is a good way to avoid getting shot, and your own shots will be more accurate if you\'re lying down.  Practice changing your stance using the Stance Up and Stance Down Buttons.  Go prone and crawl under the barbed wire.',
  '除了站立，你还可以蹲下和卧倒。在战场上，压低身体是避免中弹的好办法，卧倒时你的射击也会更精确。用站起和蹲下键练习更换姿势。卧倒并从铁丝网下面爬过去。'),
 ('The other soldiers in your platoon are in the courtyard below.  Press the Command Map Button to call up the command interface.',
  '你小队的其他队员在下面的院子里。按指挥地图键调出指挥界面。'),
 ('Your platoon is organized into two fireteams.  You\'re in Fireteam Alpha.  You can tell a fireteam where to move by selecting it in the command map interface and placing waypoints on the map.  Use the µ button to add a waypoint, and press the ± button  to remove it.  Practice giving movement orders to Fireteam Bravo.  Switch in and out of the command map interface to watch them follow your orders.',
  '你的小队分为两个战斗小组。你在A组。在指挥地图界面选中一个战斗小组并在地图上放置路径点，就可以命令它移动。按 µ 键添加路径点，按 ± 键删除。练习给B组下达移动命令。进出指挥地图界面观察他们执行你的命令。'),
 ('If you hold the µ button down while adding a waypoint you\'ll see a firing arc. Using the directional buttons (or left analog stick) changes the direction of the firing arc.  You can use this to tell a fireteam to direct their shots in a particular direction.  It\'s good for snipers or for laying down cover fire.',
  '添加路径点时按住 µ 键会出现一个射击扇面。用方向键（或左摇杆）可以改变射击扇面的朝向。你可以用它命令战斗小组朝特定方向射击。这适合狙击手或压制火力。'),
 ('The Command interface determines each fireteam\'s rules of engagement or ROE.  Using the movement ROE you can order a fireteam to Hold, Advance, or Advance At All Costs.  Fireteams will automatically switch from Advance to Hold if they\'re in danger.  If you want them to keep moving no matter what, set them to Advance At All Costs.  Practice changing the movement ROE for your fireteams.',
  '指挥界面决定每个战斗小组的交战规则。用移动交战规则你可以命令战斗小组待命、前进或不惜一切代价前进。战斗小组遇到危险时会自动从前进切换为待命。如果你想让他们不顾一切继续推进，就设为不惜一切代价前进。练习改变你战斗小组的移动交战规则。'),
 ('The combat ROE is used to set the aggression level of each fireteam.  Recon means the fireteam will try to avoid contact with the enemy, but will return fire if attacked.  Assault is the default - the fireteam will engage any targets they see.  Suppress is the most aggressive - the fireteam will lay down cover fire in the general direction of the enemy and try to keep them pinned down',
  '战斗交战规则用来设定每个战斗小组的攻击性。侦察的攻击性最低——战斗小组会尽量避免与敌军交战，但遭到攻击时也会还击。突击是默认状态——战斗小组会向他们看到的敌人发动进攻。压制最为激进——战斗小组会朝敌人方向进行压制火力射击，尽量压住敌人。'),
 ('Choose in the Command Interface to switch to the change soldier/ROE page.  Here you can check on the status of the rest of your platoon.  Practice switching between soldiers using left analog stick and µ button.',
  '在指挥界面中选择可切换到队员/交战规则页面。在这里你可以查看小队其他队员的状态。练习用左摇杆和 µ 键在队员之间切换。'),
 ('This concludes your Ghost Recon basic training.  Press the START button at any time to exit training.',
  '游戏的基本训练到此结束。随时按 START 键退出训练。'),
 ('Training', '训练'),
 ('T01 - Obstacle Course', '训练1 - 越野训练'),
 ('Ft. Bragg, NC', '布拉格堡, 北卡罗来纳州'),
 ('March 15, 2008', '2008年3月15日'), ('13:00', '13:00'),
 # ---------------- MP map labels (G34-39 / G53-57) ----------------
 ('MP01 River', 'MP01 河流'), ('MP02 Night Battle', 'MP02 夜战'), ('MP03 Train Wreck', 'MP03 列车残骸'),
 ('MP04 Valley', 'MP04 山谷'), ('MP05 Docks', 'MP05 码头'),
 ('Lubana River, Latvia', '卢巴纳河, 拉脱维亚'), ('Venta, Lithuania', '文塔, 立陶宛'),
 ('South Ossetian Autonomous Region', '南奥塞梯自治州'),
 ('Severodvinsk, Russia', '北德文斯克, 俄罗斯'), ('Near Tacoma, WA', '塔科马附近'),
 ('Ft. Drum, NY', '德拉姆堡, 纽约州'), ('Hot Springs, CO', '温泉城, 科罗拉多州'),
 ('DP01  Stronghold', 'DP01 据点'), ('DP02  Farm Day', 'DP02 农场'), ('DP03  Creekbed', 'DP03 河床'),
 ('DP04  Wilderness', 'DP04 荒野'), ('DP05  Ravine', 'DP05 峡谷'),
 ('June 10, 2008', '2008年6月10日'), ('June 24, 2008', '2008年6月24日'), ('May 2, 2008', '2008年5月2日'),
 ('April 16, 2008', '2008年4月16日'), ('September 22, 2008', '2008年9月22日'),
 ('April 10, 2009', '2009年4月10日'), ('April 24, 2008', '2008年4月24日'),
 ('April 12, 2009', '2009年4月12日'), ('April 14, 2009', '2009年4月14日'),
 ('April 16, 2009', '2009年4月16日'),
 ('10:00', '10:00'), ('02:15', '02:15'), ('15:00', '15:00'), ('18:00', '18:00'),
 ('09:00', '09:00'), ('06:00', '06:00'), ('11:15', '11:15'), ('16:00', '16:00'),
 # ---------------- pool-group dialogs 31-200B ----------------
 ('Quit to the main menu without saving?', '不保存就退回主菜单吗？'),
 ('You will lose your data if you go back without saving, do you want to save?', '不保存就返回会丢失数据，要保存吗？'),
 ('Learn the basic controls of the game.', '学习游戏的基本操作。'),
 ('Apprehend battlefield situations and learn more about tactical warfare.', '了解战场形势，学习更多战术知识。'),
 ('Enter the main mission based game mode.', '进入以任务为主的游戏模式。'),
 ('Replay mission in different modes or levels.', '以不同模式或难度重玩任务。'),
 ('Co-operative or one on one, the more the better.', '合作或单挑，人越多越好。'),
 ('Check your game progress and access rewards.', '查看你的游戏进度并领取奖励。'),
 ('Check the ranking of this mission.', '查看本任务的最佳纪录。'),
 ('Change controls, screen and sound options.', '更改操作、画面和声音选项。'),
 ('Understand battlefield situations and learn more about tactical warfare.', '了解战场形势，学习更多战术知识。'),
 ('View more detailed information.', '查看更详细的信息。'),
 ('Choose among the three configurations.', '在三种设置中选择一种。'),
 ('Adjust right analog stick sensitivity.', '调整右摇杆灵敏度。'),
 ('Adjust the center position of the screen.', '调整屏幕的中心位置。'),
 ('Adjust the background music volume.', '调整背景音乐音量。'),
 ('Toggle surround sound on or off.', '开启或关闭环绕声。'),
 ('Reach the extraction point safely.', '安全到达撤离点。'),
 ('Beat you time to accomplish the objectives.', '打破你的纪录并完成目标。'),
 ('Enter the real battlefield to prove your value.', '进入真正的战场证明你的价值。'),
 ('Check your objectives carefully.', '仔细查看你的任务目标。'),
 ('Left and right to select soldier.', '左右键选择队员。'),
 ('Left and right to change soldiers order.', '左右键更换队员顺序。'),
 ('Assign the platoon automatically.', '自动分配小队。'),
 ('Assign combat points to the soldiers.', '给队员分配战斗点数。'),
 ('Enter save name for replay file.', '输入重放文件的保存名称。'),
 ('Load the last saved game, restart the action, or repick your team?', '载入最近一次的存档、重新开始本关，还是重新选择小组？'),
 ('Are you sure to delete profile "%0"?', '你确定要删除档案"%0"吗？'),
 ('Are you sure you want to delete the save file?', '你确定要删除这个存档吗？'),
 ('Are you sure you want to delete the replay?', '你确定要删除这个重放文件吗？'),
 ('Loading Mission... Please Wait.', '载入任务中... 请稍候。'),
 ('Are you sure you want to Abort and return to Briefing?', '你确定要中止并返回简介吗？'),
 ('Are you sure you want to quit the game to restart the mission?', '你确定要退出并重玩本关吗？'),
 ('Are you sure you want to quit the game to pick another training mission?', '你确定要退出并选择另一个训练关吗？'),
 ('ESTIMATED REMAINING MISSION TIME: ', '估计任务剩余时间: '),
 ('Learn to navigate complex obstacles created for true tactical training.', '学习适应各种复杂的地形条件和障碍物。'),
 ('To unlock further missions, you must first complete the current mission.', '要进入后面的关卡，你必须先通过本关。'),
 ('Toggles between difficulty levels.', '在各难度等级之间切换。'),
 ('Every soldier against each other.', '所有队员混战。'),
 ('Every soldier against each other. No mission Voting.', '所有队员混战。无任务投票。'),
 ('Team vs. Team. No mission Voting.', '小组对战。无任务投票。'),
 ('Fight the machine. No mission Voting.', '与电脑对战。无任务投票。'),
 ('Two players head to head. No mission Voting.', '两个玩家对战。无任务投票。'),
 ("'Veteran' is easier than 'Elite' but certainly isn't for Rookies!", '"老兵"比"精英"容易，但也绝不是给新手玩的!'),
 ("'Legendary' is for the best of the best of the best.", '"传奇"只属于精英中的精英。'),
 ('Request for team assignment denied: ', '分配小组的要求被拒绝: '),
 ('Request for observer mode denied: server setting does not allow observers.', '使用观看模式的要求被拒绝: 服务器设置不允许观看。'),
 ('Equip some Demo Charges before trying this mission.', '在进入游戏前，多装备一些定时炸弹。'),
 ('Demo Charges are recommended. Press yes to continue or no to re-equip.', '建议装备定时炸弹。按"是"继续，按"否"更换装备。'),
 ('Equip an M136 before trying this mission.', '在进入游戏前，先装备一个M136。'),
 ('M136s are recommended. Press yes to continue or no to re-equip.', '建议装备一些M136。按"是"继续，按"否"更换装备。'),
 ('Are you sure you want to overwrite this save game?', '你真的要覆盖这个游戏存档？'),
 ('A Replay file with that name already exists, Overwrite?', '已经有同名的重放文件，要覆盖吗？'),
 ('Error: Invalid chracters in the save name. Replay not saved.', '出错: 保存名称里有无效字符，重放文件未保存。'),
 ('Are you sure you want to overwrite this profile?', '你确定要覆盖这个档案吗？'),
 ('Wrong password given: Try again?', '密码错误，重试？'),
 ('Maximum allowable number of players cannot exceed ', '玩家数目不能超过 '),
 ('Allow Observers disabled: Resetting observers', '允许观看已关闭: 正在重设观看者'),
 ('AI Backup request denied: Server Game Mode: Solo', '电脑支援请求被拒绝: 服务器游戏模式: 单人'),
 ('Random Teams in use: Unassigning all players', '随机小组正在使用中: 正在取消所有玩家分配'),
 ('Only fireteams A and B are available in coop', '合作模式中只有A组和B组可选'),
 ('Vote not allowed: player not on platoon', '不允许投票: 玩家不在团队中'),
 ('SELECT TACTICAL EXERCISE MISSION', '选择战术演习任务'),
 ('Cannot enable respawn: AI Backup Enabled', '无法开启重生: 已开启电脑支援'),
 ('Cannot change setting for platoon ', '无法更改小队设置 '),
 ('Cannot change difficulty settings: ', '无法更改难度设置: '),
 ('Cannot enable Random Insertion zones: ', '无法使用随机突入区: '),
 ('A vote to eject a player has been requested. Eject:  ', '有人请求投票踢掉一个玩家。踢掉:  '),
 ('Cannot connect to this server: ', '无法连接这个服务器: '),
 ('Do you wish to force out the client?', '你要强制断开客户机吗？'),
 ('Access to Server setup revoked: Server forced you off', '进入服务器设置被拒绝: 服务器强制把你移出'),
 ('Are you sure you want to Abort the Playback?', '你真的要中止播放吗？'),
 ('Please edit the server to activate at least two platoons for team mode ', '请编辑服务器，确保小组模式至少有2个团队 '),
 ('Waiting for other players to join.', '等待其他玩家加入。'),
 ('You will lose your progress if you Quit. Continue?', '如果你现在退出，游戏内容将全部丢失。要继续吗？'),
 ('Are you sure? You will lose your progress for this mission.', '你确定吗？你将丢失本任务的进度。'),
 ('Are you sure you want to quit to the main menu?', '你真的要退出游戏返回主菜单吗？'),
 ('A Server Script file with that name already exists, Overwrite?', '已经有同名的服务器文件，要覆盖吗？'),
 ("Server's information is not available at this time.", '目前无法获得服务器信息。'),
 ('Server has cancelled the vote to launch the game. Prepare to launch', '服务器已经取消了开始游戏的投票。准备开始'),
 ('A vote to eject a player is underway. Do you still wish to launch the game?', '正在投票是否踢掉一个玩家，你仍然要开始游戏吗？'),
 ('Downloading data from the server', '正在从服务器下载数据'),
 ('To deactivate: Make and accept changes to settings or load a new script.', '要让它中止: 确认更改或者载入新的文件。'),
 ('Do you want to save your new profile now?', '要现在保存你的新档案吗？'),
 ('Do you want to save the current progress?', '要保存当前进度吗？'),
 ('Do you want to save the current options?', '要保存当前设置吗？'),
 ('Unformatted memory card (8MB) (for PlayStation®2). Press X button to continue.',
  '记忆卡(8MB) (for PlayStation®2) 未格式化。按 X 键继续。'),
 ('No memory card (8MB) (for PlayStation®2) in MEMORY CARD slot 1.',
  '记忆卡槽1里没有记忆卡(8MB) (for PlayStation®2)。'),
 ('Data on memory card (8MB) (for PlayStation®2) in MEMORY CARD slot 1 has changed.',
  '记忆卡槽1里记忆卡(8MB) (for PlayStation®2) 上的数据已更改。'),
 ('Save failed! Memory card (8MB) (for PlayStation®2) in MEMORY CARD slot 1 error!',
  '保存失败! 记忆卡槽1里的记忆卡(8MB) (for PlayStation®2) 出错!'),
 ("Tom Clancy's Ghost Recon data already exists. Overwrite previous data?",
  '已有《幽灵行动》的存档数据，覆盖以前的数据吗？'),
 ('Memory card (8MB) (for PlayStation®2) in MEMORY CARD slot 1 is unformatted.',
  '记忆卡槽1里的记忆卡(8MB) (for PlayStation®2) 未格式化。'),
 ('Load Failed! Memory card (8MB) (for PlayStation®2) in MEMORY CARD slot 1 error!',
  '读取失败! 记忆卡槽1里的记忆卡(8MB) (for PlayStation®2) 出错!'),
 ('Proceed to the next mission without saving?', '不保存就进入下一个任务吗？'),
 ('RESTART FOR OPTION TO TAKE EFFECT', '重新开始后选项才会生效'),
 ('"%0" is currently mapped to %1%2%3.', '"%0"当前被设置为%1%2%3。'),
 ('Enter a name to save your key mappings.', '输入保存按键设置的名称。'),
 ('CANNOT CHANGE WHILE ON A MISSION', '任务中无法更改'),
 ('Insufficient space on memory card (8MB) (for PlayStation®2). Insert a memory card (8MB) (for PlayStation®2) with at least 135KB free.',
  '记忆卡(8MB) (for PlayStation®2) 空间不足。请插入一张至少有135KB剩余空间的记忆卡(8MB) (for PlayStation®2)。'),
 ('Caution! If you wish to save your game data, insert a memory card (8MB) (for PlayStation®2) with at least 135KB free.',
  '注意! 如果要保存游戏数据，请插入一张至少有135KB剩余空间的记忆卡(8MB) (for PlayStation®2)。'),
 ('Accessing memory card (8MB) (for PlayStation®2) in MEMORY CARD slot 1. Do not remove memory card (8MB) (for PlayStation®2), reset, or switch off the console.',
  '正在读取记忆卡槽1里的记忆卡(8MB) (for PlayStation®2)。请勿移除记忆卡(8MB) (for PlayStation®2)、重启或关闭主机。'),
 ('Format failed! Please check memory card (8MB) (for PlayStation®2) in MEMORY CARD slot 1 and try again.',
  '格式化失败! 请检查记忆卡槽1里的记忆卡(8MB) (for PlayStation®2) 后重试。'),
 ('Formatting memory card (8MB) (for PlayStation®2) in MEMORY CARD slot 1. Do not remove memory card (8MB) (for PlayStation®2), reset, or switch off the console.',
  '正在格式化记忆卡槽1里的记忆卡(8MB) (for PlayStation®2)。请勿移除记忆卡(8MB) (for PlayStation®2)、重启或关闭主机。'),
 ('Insufficient space on memory card (8MB) (for PlayStation®2) in MEMORY CARD slot 1. Tom Clancy\'s Ghost Recon needs at least 135KB free.',
  '记忆卡槽1里的记忆卡(8MB) (for PlayStation®2) 空间不足。《幽灵行动》至少需要135KB空间。'),
 ('Load failed! Check memory card (8MB) (for PlayStation®2) in MEMORY CARD slot 1 and please try again.',
  '读取失败! 请检查记忆卡槽1里的记忆卡(8MB) (for PlayStation®2) 后重试。'),
 ('Load the last saved game, restart the action, or repick your team? You will lose your progress for this mission.',
  '载入最近一次的存档、重新开始本关，还是重新选择小组？你将丢失本任务的进度。'),
 ('Loading data. Do not remove memory card (8MB) (for PlayStation®2) in MEMORY CARD slot 1, reset, or switch off the console.',
  '正在读取数据。请勿移除记忆卡槽1里的记忆卡(8MB) (for PlayStation®2)、重启或关闭主机。'),
 ('Memory card (8MB) (for PlayStation®2) in MEMORY CARD slot 1 is unformatted. Format  memory card (8MB) (for PlayStation®2)?',
  '记忆卡槽1里的记忆卡(8MB) (for PlayStation®2) 未格式化。要格式化记忆卡(8MB) (for PlayStation®2) 吗？'),
 ("No Tom Clancy's Ghost Recon save data present on memory card (8MB) (for PlayStation®2) in MEMORY CARD slot 1.",
  '记忆卡槽1里的记忆卡(8MB) (for PlayStation®2) 上没有《幽灵行动》的存档数据。'),
 ('Overwrite failed! Check memory card (8MB) (for PlayStation®2) in MEMORY CARD slot 1 and please try again.',
  '覆盖失败! 请检查记忆卡槽1里的记忆卡(8MB) (for PlayStation®2) 后重试。'),
 ('Overwrite failed! Memory card (8MB) (for PlayStation®2) in MEMORY CARD slot 1 error!',
  '覆盖失败! 记忆卡槽1里的记忆卡(8MB) (for PlayStation®2) 出错!'),
 ('R1                                                                                 L1', 'KEEP'),
 ('Record aborted, all Replay information to this point will be lost. New Replay recording started.',
  '记录被中止，所有重放信息丢失。新的重放记录开始。'),
 ('Save failed! Check memory card (8MB) (for PlayStation®2) in MEMORY CARD slot 1 and please try again.',
  '保存失败! 请检查记忆卡槽1里的记忆卡(8MB) (for PlayStation®2) 后重试。'),
 ('Saving data. Do not remove memory card (8MB) (for PlayStation®2) in MEMORY CARD slot 1, reset, or switch off the console.',
  '正在保存数据。请勿移除记忆卡槽1里的记忆卡(8MB) (for PlayStation®2)、重启或关闭主机。'),
 ('Since the number of files will exceed the limit, no additional files can be created. Are you sure? Yes/No',
  '文件数目将超过上限，无法再建立新文件。你确定吗？是/否'),
 ('Overwriting data.  Do not remove memory card (8MB) (for PlayStation®2) in MEMORY CARD slot 1, reset, or switch off the console.',
  '正在覆盖数据。请勿移除记忆卡槽1里的记忆卡(8MB) (for PlayStation®2)、重启或关闭主机。'),
 ('The server is running the following modifications which you do not have installed:',
  '服务器使用了你没有安装的以下MOD:'),
 ('Are you sure you wish to format memory card (8MB) (for PlayStation®2) in MEMORY CARD slot 1?',
  '你确定要格式化记忆卡槽1里的记忆卡(8MB) (for PlayStation®2) 吗？'),
 # extra credit roles (>30B)
 ('<title>Supervising Sound Designer', '<title>监督声音设计师'),
 ('<title>Sound Designer/Gun Recordist', '<title>声音设计师/枪声录音师'),
 ('<title>International Production Director', '<title>国际制作总监'),
 ('<title>International Content Manager', '<title>国际内容经理'),
 ('<title> Worldwide Localization Manager', '<title>全球本地化经理'),
 ('<title> Localization Project Manager', '<title>本地化项目经理'),
 ('<title>Assistant to Managing Director', '<title>总裁助理'),
 ('<title>Programmer Studio Manager', '<title>程序工作室经理'),
 ('<title>Info Design Studio Manager', '<title>信息设计工作室经理'),
 ('<title>Game Design Studio Manager', '<title>游戏设计工作室经理'),
])

# extra legal keeps (credits legal block)
LEGAL2 = {
    'RED STORM AND RED STORM ENTERTAINMENT', 'RED STORM ENTERTAINMENT, INC. IS A',
    'UBI SOFT ENTERTAINMENT COMPANY.', 'TRADEMARK OF JACK RYAN ENTERPRISES, LTD.',
    'UNDER LICENSE TO UBI SOFT ENTERTAINMENT.', 'UBI SOFT LOGO ARE REGISTERED TRADEMARKS',
    'OF UBI SOFT ENTERTAINMENT.  ALL OTHER', 'TRADEMARKS ARE THE PROPERTY OF THEIR',
    '<TITLE>RED STORM ENTERTAINMENT INC.', '<TITLE>UBISOFT ENTERTAINMENT EMEA',
    'SOUNDELUXE CREDITS', 'UBISOFT PRESENTS',
}

def zh_of(en: str):
    return T.get(norm(en).upper())
